import type { NextPage } from 'next'
import Head from 'next/head'
import SectionAbout from "../components/SectionAbout"

const About: NextPage = () => {
  return (
    <div className="about">
      <Head>
        <title>about page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionAbout />
    </div>
  )
}

export default About
