import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import SectionDashbord from '../components/SectionDashbord'
import FixedBottomBtn from '../components/FixedBottomBtn'

const DynamicComponentWithNoSSR = dynamic(() => import('../components/SectionDashbord'), {
  ssr: false,
})

const Dashbord: NextPage = () => {
  return (
    <div className='dashbord'>
      <Head>
        <title>dashbord</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DynamicComponentWithNoSSR />

      {/* <FixedBottomBtn /> */}
    </div>
  )
}

export default Dashbord
