import type { NextPage } from 'next'
import Head from 'next/head'
import SectionDisc from '../components/SectionDisc'

const disc: NextPage = () => {
  return (
    <div className='disc'>
      <Head>
        <title>情報の使い方</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SectionDisc />
    </div>
  )
}

export default disc
