import type { NextPage } from 'next'
import Head from 'next/head'
import SectionLogin from "../components/SectionLogin";
import SectionHeader from "../components/SectionHeader";

const Login: NextPage = () => {
  return (
    <div className="login _flex_c_">
      <Head>
        <title>Login App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionLogin />
    </div>
  )
}

export default Login
