import type { NextPage } from 'next'
import Head from 'next/head'
import SectionMakeStructure from '../components/SectionMakeStructure'

const disc: NextPage = () => {
  return (
    <div className='disc'>
      <Head>
        <title>構造 レベルの作成</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SectionMakeStructure />
    </div>
  )
}

export default disc
