import type { NextPage } from 'next'
import Head from 'next/head'
import SectionSearcher from '../components/SectionSearcher'

const searcher: NextPage = () => {
  return (
    <div className='searcher'>
      <Head>
        <title>情報の使い方</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SectionSearcher />
    </div>
  )
}

export default searcher
